### ISSUE TITLE
Treffendere Bezeichnung für oparl:Paper gesucht

### ISSUE THREAD

**Issue by akuckartz** [OParl/specs#126]
Die Bezeichnungen Document und Paper sind leicht verwechselbar. Die Umbenennung eines der beiden scheint sinnvoll zu sein.

**Comment by eFrane** [comment]
Oparl:Document heißt laut geraumer Zeit OParl:File. Ich schließe das Issue damit. Wenn weiterer Diskussionsbedarf besteht, bitte in einem neuen Issue.
