### ISSUE TITLE
Cross-Origin Resource Sharing (CORS)

### ISSUE THREAD

**Issue by akuckartz** [OParl/specs#228]
Ein Vorschlag von @lanthaler in https://github.com/OParl/specs/issues/67#issuecomment-47465719

> Wird auf CORS Unterstützung komplett verzichtet? Ich denke das wäre auf jeden Fall
> ein Fehler. Zum einen wird es bereits sehr gut von Browsern unterstützt
> (http://caniuse.com/cors) und der Implementierungsaufwand ist extrem gering. In der
> Regel ist nur ein einziger zusätzlicher HTTP Header auszugeben:
> Access-Control-Allow-Origin: * (http://enable-cors.org/server.html)
> 
> Ich würde daher vorschlagen CORS als MUSS in die Spec aufzunehmen.

Cross-Origin Resource Sharing
W3C Recommendation 16 January 2014
http://www.w3.org/TR/cors/

**Comment by eFrane** [comment]
Da hier das Resultat bisher unklar ist: Der CORS-Header verbleibt bis auf weiteres optional, aber empfohlen, um die Notwendigkeit der Implementation von spezieller HTTP-Headern auf Servern zu vermeiden. 

Zudem bleibt die Frage, ob OParl 1.0 überhaupt von Webentwicklern von Browsern aus angefragt werden wird und CORS einen Nutzen haben würde.

**Comment by akuckartz** [comment]
> Da hier das Resultat bisher unklar ist: Der CORS-Header verbleibt bis auf weiteres optional, aber empfohlen, um die Notwendigkeit der Implementation von spezieller HTTP-Headern auf Servern zu vermeiden.

Es gibt hier wenige Issues deren Ergebnis derart klar und eindeutig war wie bei diesem: mehrere Befürworter von MUSS und niemand dagegen. Deshalb hatte Marian dies im Konsens aufgenommen. Gibt es einen Server-Hersteller, dem das Probleme bereitet? Dann sollte er sich hier äußern.

> Zudem bleibt die Frage, ob OParl 1.0 überhaupt von Webentwicklern von Browsern aus angefragt werden wird und CORS einen Nutzen haben würde.

Ohne CORS wird die Anzahl solcher Nutzer mit Sicherheit sehr nahe bei Null liegen. OpenGovLD wird jedenfalls weiter die CORS-Unterstützung durch Server voraussetzen.

**Comment by akuckartz** [comment]
Zudem wird in der aktuellen Version des Textes zwingend gefordert, dass Server CORS unterstützen...

Der Kommentar https://github.com/OParl/specs/issues/228#issuecomment-112154166 ergibt daher auch in dieser Hinsicht keinen Sinn.

**Comment by black-snow** [comment]
Ich würde empfehlen nicht zu spekulieren wer eventuell die Services wie nutzt sondern im Gegenteil versuchen niemandem Steine in den Weg zu legen und möglichst viele abzuräumen. CORS ist eigentlich keine große Sache und sollte imho gefordert bleiben oder zumindest wärmstens empfohlen.

OT: @akuckartz dein Kommentar klingt sehr offensiv. Sicherlich möchtest du hier keinen persönlich angreifen - ich würde einen positiv-konstruktiveren Ton empfehlen. Solche Projekte funktionieren nur gut wenn die Leute (mit Freude) zusammenarbeiten. Ich kann natürlich nicht für eFrance sprechen aber ich hoffe du verstehst worauf ich hinaus will und man verzeiht mir, dass ich mich hier einmische.

Sonnigen Gruß!

**Comment by marians** [comment]
nachdem ich mich gerade von berufswegen mit einer CORS-Implementierung herumgeschlagen habe, kann ich als Erfahrung beisteuern, dass CORS in der Praxis nicht mit dem Ausgaben eines einzigen weiteren Response Headers erledigt ist.

Browser wie z. B. Chrome machen sog. "preflight requests", bei der die `OPTIONS` HTTP-Methode verwendet wird. Wird diese Anfrage vom Server nicht unterstützt, untersagt der Browser jede weitere Anfrage an dieselbe URL. In der Antwort auf solche Requests müssen u. a. alle Request Header, die bei weiteren Anfragen verwendet werden dürfen, aufgelistet werden (`Access-Control-Allow-Headers`). Es gibt keine wildcard-Option.

Die richtige Beantwortung der OPTIONS-Anfragen ist also ein Punkt, der CORS-Unterstützug für die Server-Implementierer wieder ein bisschen komplizierter macht. Web-Client-Entwickler hingegen, die mit einer Server-API kommunizieren wollen, die CORS nicht unterstützt, können sich helfen, indem sie selbst einen Proxy-Server betreiben. Hier ist eine beispielhafte nginx Konfiguration:

```
error_log stderr warn;
worker_processes 1;
events {
  worker_connections 100;
}
http {
  log_format custom '"$request" '
      '$status $body_bytes_sent $request_time '
      '"$http_x_forwarded_for" '
      '"$http_user_agent" "$http_referer"';
  server {
    listen 80;
    access_log  /dev/stdout  custom;
    location / {
      if ($request_method = 'OPTIONS') {
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Max-Age' 1728000;
        add_header 'Content-Type' 'text/plain charset=UTF-8';
        add_header 'Content-Length' 0;
        add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization';
        return 204;
      }
      if ($request_method = 'POST') {
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, DELETE';
        proxy_pass https://api.giantswarm.io;
      }
      if ($request_method = 'GET') {
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, DELETE';
        proxy_pass https://api.giantswarm.io;
      }
      if ($request_method = 'DELETE') {
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, DELETE';
        proxy_pass https://api.giantswarm.io;
      }
    }
  }
}```

Vor diesem Hintergrund würde ich von meiner früheren MUSS-Empfehlung abrücken und nunmehr SOLL empfehlen.

+1 für positiv-konstruktiven Ton.

**Comment by akuckartz** [comment]
@marians Guter Hinweis, auch wenn ich die Schlussfolgerung ("nunmehr SOLL empfehlen") nicht teile. Ich möchte noch einmal auf die Implementierungstipps http://enable-cors.org/server.html hinweisen. Zum Verständnis der "preflight requests" kann eventuell http://www.html5rocks.com/en/tutorials/cors/ beitragen.

Mein Interesse an diesem Issue ist recht einfach: ohne Unterstützung von CORS auf Serverseite (und sei es über einen Proxy-Server) wird es Browsern kaum möglich sein, die ausgelieferten Daten zu verwenden. In der Hinsicht gibt es keinen Unterschied zwischen OParl und OpenGovLD. 

OT: @black-snow Das verstehe ich schon, aber es wurde offenbar eine Entscheidung des Projektes verkündet ("Der CORS-Header verbleibt bis auf weiteres optional ...") und nicht einfach eine persönliche Meinung. Und ich denke, dass ein Projekt die vorausgegangenen Kommentare von anderen zur Kenntnis nehmen sollte bevor eine Entscheidung gefällt wird. Das war hier - allem Anschein nach - nicht geschehen. Auch das gehört zu den Themen Zusammenarbeit und Transparenz. (Zudem wurden gab es hier in den letzten Tagen bereits andere Issues die mit teilweise sehr fragwürdiger Begründung geschlossen wurden. Dem passe ich dann auch meinen Ton _etwas_ an.)

**Comment by lu-j** [comment]
Vielen Dank für euer Feedback und die nginx Konfiguration!

Soweit ich weiß, sind preflight requests nur notwendig, wenn Anfragen gemacht werden, die keine "simple requests" sind. Simple requests sind alle Anfragen, die auch mit einem gewöhnlichen HTML Formular an einen fremden Server gemacht werden könnten.

Es kann aber gut sein, dass es in der Praxis anders aussieht und Browser immer preflight requests machen. @marians hast du hier Erfahrungen?

Ich bin auch dafür CORS nicht verpflichtend zu machen. Dafür habe ich zwei Gründe:

1. Die neue Zielsetzung für OParl 1.0 (siehe #278) sieht vor, dass es mit OParl möglich sein soll, die OParl-Daten in eine eigene Datenbank zu laden. Sonstige Abfragemöglichen, zum Beispiel Suchen und Sortieren, sind in Version 1.0 noch nicht vergesehen. Ich glaube kaum, dass jemand eine solche API direkt vom Browser aus ansprechen will, falls doch ist das mit einem Proxy möglich. Für Server die über OParl 1.0 hinausgehende Abfragemöglichkeiten anbieten, ist es natürlich sinnvoll CORS zu unterstützen.

2. Wenn auch die Forderung in Issue #276 umgesetzt wird, kann man einen OParl Server betreiben, ohne spezielle HTTP-Header unterstzützen zu müssen. Das finde ich wichtig, da RISe hinter verschiedensten Webservern und Reverse Proxies betrieben werden, worauf die RIS-Hersteller keinen Einfluss haben. Ich möchte vermeiden, dass für OParl die Serverkonfiguration geändert werden muss, um bestimmte Header unterstützen zu können. Es kann natürlich sein, dass ich das falsch Einschätze und der Aufwand für die Unterstützung spezieller Header geringer ist als gedacht. Ich möchte OParl 1.0 aber so simpel wie möglich halten, daher finde ich Anforderungen sollten nur zwingend sein, wenn sie für den Betrieb eines OParl-Server auch tatsächlich zwingend notwendig sind.

**Comment by akuckartz** [comment]
@lu-j Die Argumentation kann ich weitgehend nachvollziehen. Dennoch zwei Punkte:

> Sonstige Abfragemöglichen, zum Beispiel Suchen und Sortieren, sind in Version 1.0 noch nicht vorgesehen. Ich glaube kaum, dass jemand eine solche API direkt vom Browser aus ansprechen will, falls doch ist das mit einem Proxy möglich. 

Es ist möglich lokal in einem Browser Suchen und Sortieren durchzuführen. Dazu müssen die Daten aber vorher durch den Browser von Servern geholt werden können (PDF-Dateien etc. ignoriere ich hier). Ohne CORS wird das schwierig oder unmöglich.

> da RISe hinter verschiedensten Webservern und Reverse Proxies betrieben werden, worauf die RIS-Hersteller keinen Einfluss haben.

Solche Anforderungen richten sich mögöicherweise in erster Linie an die Betreiber der Infrastruktur und weniger an RIS-Hersteller. Zischen welche Komponenten OParl Schnittstellen spezifizieren möchte ist mir aktuell nicht klar (zwischen Server und Browser offenbar gegenwärtig nicht), Es kann entscheidend sein, ob es (nur) um eine Schnittstelle zwischen Servern und Proxy-Servern geht oder z.B. um Schnittstellen zwischen Servern und allgemeineren Nicht-Browser-Clients.

Nebenbei: Der aktuelle Stand des Spezifikationsentwurfs enthält eine MUSS-Formulierung bezüglich CORS. Insofern wäre eventuell eine Wieder-Öffnung dieses Issue angebracht.
