### ISSUE TITLE
Behandlung von "@"-Eigenschaften entsprechend herstellerspezifischen Erweiterungen

### ISSUE THREAD

**Issue by akuckartz** [OParl/specs#246]
Da JSON-LD in OParl nach aktuellem Stand nicht berücksichtigt wird, sollten Eigenschaften deren Name mit "@" beginnt ähnlich wie herstellerspezifische Eigenschaften berücksichtigt werden. Siehe dazu Abschnitt "5.1.6 Herstellerspeziﬁsche Erweiterungen".

Rein formell ist das zwar kein Unterschied zum bisherigen Stand des Dokuments, da an keiner Stelle die Ausgabe zusätzlicher Eigenschaften ohne Präfix durch Server ausgeschlossen ist (was möglicherweise geändert werden sollte, mit Ausnahme der "@"-Eigenschaften). Es hilft aber zur Klarstellung und erleichtert potentiell die Implementierung polyglotter Server, also solcher die sowohl konform zu OParl als auch konform zu anderen auf JSON-LD beruhenden Spezifikationen sind.

**Comment by the-infinity** [comment]
Fixed mit https://github.com/OParl/specs/commit/539542c46f572a58bc47a59d69cfa0bdac1086e1 .
