### ISSUE TITLE
Milestone "1.0 Freigabe" überfällig

### ISSUE THREAD

**Issue by akuckartz** [OParl/specs#261]
Der für Milestone "1.0 Freigabe" angegebene Termin ist seit über einem Monat verstrichen. Eine Aktualisierung (oder Löschung) des geplanten Termins wäre deshalb möglicherweise sinnvoll.

**Comment by akuckartz** [comment]
Laut https://github.com/OParl/specs/milestones ist der Milestone "1.0 Freigabe" nun 7 Monate überfällig. Weder wurden im letzten halben Jahr Issues bearbeitet (wenn man von meinen Kommentaren absieht), noch wurde die Spezifikation verbessert, noch wurde die Zeitplanung aktualisiert, noch wurde oparl.org aktualisiert.

 Ich gehe deshalb davon aus, dass das OParl-Spezifikationsprojekt nicht weiter aktiv ist.

Das bedeutet aber keineswegs, dass die Bedarf einer zeitgemäßen, zukunftssicheren und nachhaltigen Spezifikation für parlamentarische Daten nicht mehr existiert. Das Gegenteil ist der Fall.

Die bis zum 4.7.2014 von OParl verfolgte Zielsetzung wird in dem Projekt OpenGovLD (https://github.com/OpenGovLD/specs/wiki) weiter verfolgt. Das Projekt findet unter dem Dach der Open Government Community Group des W3C statt (http://www.w3.org/community/opengov/). Allerdings ist die Zielsetzung von OpenGovLD weitreichender als die ursprünglich von den OParl-Initiatoren vorgeschlagene und insbesondere nicht auf Deutschland beschränkt.

Jeder bisherige Interessent an OParl ist aufgerufen, Mitglied dieser Community Group des W3C zu werden und an der Entwicklung von OpenGovLD mitzuarbeiten.

**Comment by astro** [comment]
Wir bei offenesdresden.de fragen uns das auch. Wir haben natürlich nach Verbesserungspunkten geschaut, jedoch die aktuelle Version für brauchbar befunden.

Eine **1.0** ohne "Entwurf" erscheint wesentlich verlässlicher wenn man die Politik auffordert den Standard zu unterstützen. Auch eine 1.0 verhindert keine 1.1 oder 2.0 mit Fehlerkorrekturen.

**Comment by akuckartz** [comment]
@astro Ich würde es für unseriös halten, wenn eine Spezifikation zu einem "Standard" erklärt würde - noch dazu in einer "Version 1.0" -, zu der es seit einem halben Jahr diverse teilweise erhebliche unbearbeitete offene Issues gibt, um die sich ersichtlich niemand kümmert. Ich hielte das schlicht für Roßtäuscherei. Auf eine solche Ebene sollten sich Open Data- oder Open Government-Unterstützer nicht begeben.

Dass damit "die Politik" getäuscht werden soll macht dies nicht besser. Tatsächlich wären das Ziel solcher Täuschungen insbesondere Verwaltungsmitarbeiter die z.B. rechtlich einwandfreie Vergabeverfahren durchführen müssen.

Ich frage mich, woraus sich die Hoffnung nährt, dass ein inaktives Spezfikationsprojekt in Zukunft Fehlerkorrekturen vornimmt oder gar neue Versionen produziert. Auch das unbegründete Schüren solcher Illusionen halte ich nicht für seriös.

**Comment by akuckartz** [comment]
Ping. Inzwischen 11 Monate überfällig.

**Comment by astro** [comment]
Hach.

**Comment by akuckartz** [comment]
Ich habe gerade gesehen, dass der Zieltermin für den Milestone "1.0 Freigabe" zwischenzeitlich gelöscht wurde. Damit ist dieses Issue in gewisser Weise erledigt.

**Comment by eFrane** [comment]
Stimmt, das Enddatum wurde zwischenzeitlich entfernt um weitere Verwirrung darüber zu vermeiden, wann genau was passiert. 

Wir sind momentan dabei, die Infrastruktur des Projektes zu überarbeiten. Wie allerdings in den vergangenen Wochen deutlich geworden sollte arbeiten wir auf einen baldigen Abschluss einer 1.0 Version hin.
