### ISSUE TITLE
Distanzierung von OParl Spezifikationsentwurf

### ISSUE THREAD

**Issue by akuckartz** [OParl/specs#263]
Der Spezifikationsentwurf suggeriert, dass ich diesen unterstützen würde.

Tatsächlich distanziere ich mich davon und unterstütze stattdessen die Standardisierungs-Aktivitäten der W3C Open Government Community Group (basierend insbesondere auf dem OParl-Fork OpenGovLD und auf Popolo).

Ich bitte deshalb darum, dass der OParl-Spezifikationsentwurf zeitnah verbessert wird.

Konkret schlage ich diese Änderungen in zwei Kapiteln vor:
- chapter_1030: Ergänzter EIntrag:

> April bis Juni 2014: Verfeinerung des in diesem Zeitraum auf JSON-LD basierenden Vokabular-Teils durch Andreas Kuckartz, finanziert durch das FP7-Projekt Fusepool aus Mitteln der Europäischen Union.

- chapter_1030: Neu:

> 4.7.2014: Entscheidung zum Rückbau von JSON-LD. Ausstieg von Andreas Kuckartz aus dem Projekt.

- chapter_1080: Ergänzung hinter meinem Namen:

> (bis 4.7.2014)

Danke.

**Comment by the-infinity** [comment]
Erledigt mit https://github.com/OParl/specs/commit/78031e180155a0f7967729e152c27fb568ebdf40 und https://github.com/OParl/specs/commit/b492ec09246f4d09673bf0658c0762f4c1abf52e .

**Comment by akuckartz** [comment]
Danke für die weitgehende Übernahme der Änderungsvorschäge.

**Comment by akuckartz** [comment]
Die "Derivate" (PDF etc.) sind noch nicht aktualisiert.
