### ISSUE TITLE
Input zu Workshop am 1.4.2015 veröffentlichen

### ISSUE THREAD

**Issue by akuckartz** [OParl/specs#272]
Nach meinen Informationen lag dem Workshop detailierter Input eines Herstellers vor. Die Veröffentlichung dieses Inputs gehört zur Transparenz die Mitte März 2015 aut oparl.org erfreulicherweise betont wurde. Dem sollten nun Taten folgen.

**Comment by the-infinity** [comment]
Die angesprochenen Punkte finden sich 1:1 in dem [Protokoll des Workshops](http://oparl.org/2015/06/06/ergebnisse-des-workshops-am-01-04-15/) wieder.
