### ISSUE TITLE
Lizenz

### ISSUE THREAD

**Issue by eFrane** [OParl/specs#280]
CC-BY-SA ist keine vollständige Lizenzangabe für Creative Commons Lizenzen, da die Versionsangabe fehlt. Mein Vorschlag wäre, CC-BY-SA 4.0 zu wählen, wenn keiner der Autoren damit ein Problem hat.

Siehe dazu auch die Hinweise [zur Wahl der Lizenzversion (und folgende)](https://wiki.creativecommons.org/wiki/Frequently_Asked_Questions#Why_should_I_use_the_latest_version_of_the_Creative_Commons_licenses.3F) von Creative Commons. 

Die wesentlichste [Neuerung in Version 4.0](https://creativecommons.org/Version4) ist die Internationalisierung der Lizenzen, was zum einen Landesportierungen überflüssig machen soll und zum anderen insbesondere auch für OParl den Vorteil bietet, dass sie nicht nur auf den deutschen bzw. europäischen Rechtsraum beschränkt ist.

Ebenso sollte mit der Anpassung der Lizenz auch die [korrekte Angabe](https://wiki.creativecommons.org/wiki/CC_REL) dieser vorgenommen werden.

**Comment by akuckartz** [comment]
:+1:

**Comment by akuckartz** [comment]
Siehe auch https://github.com/OpenGovLD/specs/issues/111 bezüglich Lizenzen für Daten oder Dokumente von Gremien.

**Comment by the-infinity** [comment]
Angenommen in https://github.com/OParl/specs/commit/7c8b5ef2545a3064f31a27fa22899c8e24429857 .
