### ISSUE TITLE
Content Negotiation entfernen, neue Eigenschaft mit der URL zur Webansicht

### ISSUE THREAD

**Issue by lu-j** [OParl/specs#284]
Auf dem Workshop wurde beschlossen:
Aktuell wird Content Negotiation empfohlen, man soll beim Aufruf einer OParl-URL im Browser auf die RIS-Webansicht für das aufgerufene Objekt weitergeleitet werden. Das würde aber das Debugging über den Browser unnötig schwer machen und OParl-Clients müssen mit einem zusätzlichem Header kommunizieren, dass sie ein OParl-Client und kein Browser sind.

Stattdessen soll es eine neue Eigenschaft geben, die die URL zur RIS-Webansicht des Objektes enthält. Diese Eigenschaft soll jedes OParl-Objekt haben können, soll aber nicht zwingend sein.

Wir bitten um Feedback!

**Comment by eFrane** [comment]
:+1:

**Comment by akuckartz** [comment]
OParl-Clients *sind* keine Web-Browser. Deshalb kann man von ihnen erwarten, dass sie das mittels der seit viielen Jahren für http standardisierten Mittel auch angeben. Weshalb ausgerechnet Webbrowser als angemessenes Werkzeug zum Debuggen von JSON angesehen werden ist mir schleierhaft.

> Stattdessen soll es eine neue Eigenschaft geben, die die URL zur RIS-Webansicht des Objektes enthält. Diese Eigenschaft soll jedes OParl-Objekt haben können, soll aber nicht zwingend sein.

Da meine Meinung dazu bekannt sein dürfte fasse ich mein Feedback schlicht so zusammen: ich schüttele den Kopf. OpenGovLD hält sich an REST- und Hypermedia-Prinzipien. Da OParl sich offenbar immer weiter von REST entfernt möchte ich verstärkt auf #268 hinweisen.

**Comment by the-infinity** [comment]
Da wir einen entwicklerfreundlichen Standard möchten und REST nicht voraussetzt, dass es eine derartige Inhaltsweiterleitung geben muss, wurde die Änderung umgesetzt in https://github.com/OParl/specs/commit/3c86513c186b788fde96afbaf4aeb663dfdf4a07
Somit closed.

**Comment by akuckartz** [comment]
Hierzu halte ich nur fest, dass das Issue bereits 8 Tage nach der Eröffnung geschlossen wurde.
