### ISSUE TITLE
Daten Dump / bulk download

### ISSUE THREAD

**Issue by akuckartz** [OParl/specs#64]
Wie kommt man am einfachsten an alle Daten auf einmal?

**Comment by akuckartz** [comment]
Ich hatte dieses von mir angelegte Issue am 4.7.2014 etwas übereilt geschlossen. Der Grund war nicht etwa, dass ich Daten Dumps nicht mehr für sinnvoll, notwendig und einfach zu implementieren halte, sondern der durch die Abwendung von JSON-LD erhöhte Aufwand.

**Comment by eFrane** [comment]
Datendumps sind mit OParl 1.0 durch einfaches rekursives durchlaufen aller Verknüpfungen ausgehend von System trivial.

**Comment by akuckartz** [comment]
@eFrane 

> Datendumps sind mit OParl 1.0 durch einfaches rekursives durchlaufen aller Verknüpfungen ausgehend von System trivial.

1. Das ist so zwar einigermaßen trivial zu implementieren, aber - wie bereits in https://github.com/OParl/specs/issues/64#issuecomment-39630503 kommentiert - praktisch unbrauchbar.

2. Auch der Workshop am 1.4.2015 hat sich dieser Auffassung offenbar angeschlossen.

Ich bitte also darum, dass dieses Issue wieder geöffnet wird.

/cc @lu-j
